// <auto-generated />
using MUDGOD.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MUDGOD.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MUDGOD.PlayerData", b =>
                {
                    b.Property<ulong>("playerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("accuracyPoints");

                    b.Property<int>("bodySize");

                    b.Property<int>("currency");

                    b.Property<int>("defPoints");

                    b.Property<int>("dexPoints");

                    b.Property<int>("fighterLevel");

                    b.Property<int>("healthPoints");

                    b.Property<int>("healthPointsMax");

                    b.Property<int>("intPoints");

                    b.Property<int>("lckPoints");

                    b.Property<int>("level");

                    b.Property<int>("locationX");

                    b.Property<int>("locationY");

                    b.Property<int>("magicianLevel");

                    b.Property<int>("manaPoints");

                    b.Property<int>("manaPointsMax");

                    b.Property<int>("myClassIdHolder");

                    b.Property<int>("myRaceIdHolder");

                    b.Property<string>("name");

                    b.Property<int>("passiveDodgePoints");

                    b.Property<int>("peasantLevel");

                    b.Property<string>("playerName");

                    b.Property<int>("rangerLevel");

                    b.Property<int>("strPoints");

                    b.Property<int>("wisPoints");

                    b.HasKey("playerId");

                    b.ToTable("playerListDB");
                });
#pragma warning restore 612, 618
        }
    }
}
